# Generated by Django 4.2 on 2023-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
