# Generated by Django 4.2 on 2023-04-26 20:52

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_picture_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=pathlib.PurePosixPath(
                    "/home/verde/VerdeRestaurant/static/images"
                ),
                upload_to="",
            ),
        ),
    ]
